### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by oonacitarhan** [CyberPunkMetalHead/Binance-volatility-trading-bot#104]
Hi guys,

First of all, great work and very clean code, it is very easy to read! I have a few suggestions:

1- "TP or SL reached" message can be changed to TP reached if it is profit; SL reached if it is loss. They are color labeled according to profit/loss but I think a text change can make it better. (But I guess it is not that simple since it is always a trailing stop loss if you make profit.)

2- While waiting for price, the coins that you have (or just # coins) can be shown (maybe even with profit/loss of each coin at that time) in the message as well.

3- In addition to session profit, total profit/loss can be showed as well. 

4- If the user runs the script on Ubuntu in a Windows machine (this is what I'm doing right now) it is Ctrl+C to quit not Ctrl+Q. Maybe this can be added to the warning at the beginning as well.

I'm very curious about this project. It looks very promising. If I survive my finals and project deadlines, I want to contribute with some coding.

**Comment by oonacitarhan** [comment]
One more thing, fees can be added to profit/loss calculation.

**Comment by eurtnl** [comment]
> 4- If the user runs the script on Ubuntu in a Windows machine (this is what I'm doing right now) it is Ctrl+C to quit not Ctrl+Q. Maybe this can be added to the warning at the beginning as well.

I tried this on MacOs and Ubuntu and indeed ctrl-Q is not working

**Comment by getsec** [comment]
@oonacitarhan Awesome feedback, Please turn that into a PR and some devs will review.
