### ISSUE TITLE
Muhammed

### ISSUE THREAD

**Issue by Muhammed0122** [CyberPunkMetalHead/Binance-volatility-trading-bot#106]
Can I activate the bot on the phone?

**Comment by getsec** [comment]
@titulebolide @Muhammed0122 

there is no support for phones. However you can clone code to a VPS and run like that. Again, not supported

**Comment by titulebolide** [comment]
Actually you can run python code and I wouldnt be surprised if it ran well on an android phone

**Comment by Muhammed0122** [comment]
> في الواقع ، يمكنك تشغيل كود Python ولن أتفاجأ إذا كان يعمل بشكل جيد على هاتف android

You mean is it possible to run it?

**Comment by TexasRaiders** [comment]
the problem I would think is latency if over cellular and it might use up your data plan if not attached to wifi.

**Comment by Muhammed0122** [comment]
> أعتقد أن المشكلة هي وقت الاستجابة إذا كانت عبر الهاتف الخلوي وقد تستهلك خطة البيانات الخاصة بك إذا لم تكن متصلة بشبكة wifi.
> 
> هذا قادر تمامًا على الركض على التوت بصفر.

Use wifi. Is there a basic plugin for bot operation?

**Comment by O-Mutt** [comment]
> Use wifi. Is there a basic plugin for bot operation?

https://lmgtfy.app/?q=running+python+code+on+android

This is not the primary use case. If you would like to add documentation on how you made it work we would love to include it as part of our README documentation. Until that point, I think this issue should be closed.
