### ISSUE TITLE
Signal tickers

### ISSUE THREAD

**Issue by VSofter** [CyberPunkMetalHead/Binance-volatility-trading-bot#107]
Hello!

Is it possible to disable signal tickers list just like in config.yml so that full coins list downloaded via Binance API?
It is analyzing only 93 default coins, while Binance has them 257 atm.

Also, why 18/26 signals condition is hardcoded? Was it made intentionally and makes some special sense?

**Comment by ShogunMan** [comment]
No, it runs independent  of binance. The best you could do is creating a custom signal tickers list with all pairs from binance.

**Comment by VSofter** [comment]
> No, it runs independent of binance. The best you could do is creating a custom signal tickers list with all pairs from binance.

Thanks. And why > 18?

**Comment by ShogunMan** [comment]
Why not, 18 of 26 indicators seems sensible. I have not got the answer to this. Its acutally just a sample of how to incorporate external signalling modules.

**Comment by VSofter** [comment]
> Why not, 18 of 26 indicators seems sensible. I have not got the answer to this. Its acutally just a sample of how to incorporate external signalling modules.

Ok, understood. Just wish it was configurable via config.yml (signals/minutes).

**Comment by ShogunMan** [comment]
Its configurable in the module

**Comment by VSofter** [comment]
> Its configurable in the module

I know, no offense :-) Just an improvement suggestion.
