### ISSUE TITLE
Binance.us support

### ISSUE THREAD

**Issue by rfidtrack** [CyberPunkMetalHead/Binance-volatility-trading-bot#11]
Will all of the calls work with binance.us?
As far as I can tell in the API docs, you just have to pass `tld='us'` when creating a new client. I can test in a day or two if you aren't able to.

**Comment by CyberPunkMetalHead** [comment]
I haven’t tested this myself, but that seems to be the only difference in the two APIs based on my reading.

**Comment by rfidtrack** [comment]
Ran it for a bit and it looks like its working (though I am hitting some of the other issues such as https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/issues/1)
