### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by keelroy** [CyberPunkMetalHead/Binance-volatility-trading-bot#111]
Fresh install. I got this:

File "D:\eth\Binance-volatility-trading-bot-main\Binance Detect Moonings.py", line 67
    old_out.write(f'{txcolors.DIM}[{str(datetime.now().replace(microsecond=0))}]{txcolors.DEFAULT} {x}')
                                                                                                      ^
SyntaxError: invalid syntax

**Comment by titulebolide** [comment]
Please give your python version (`python --version`)
f-strings (here a string prefixed by and "f") is supported solely from the version 3.6

**Comment by keelroy** [comment]
C:\Users\KeelRoy>python --version
Python 3.9.5

The error come if i start:  "Binance Detect Moonings.py" in cmd.

Problem solved, if i start:  python "Binance Detect Moonings.py"  in cmd.

**Comment by getsec** [comment]
🤪
