### ISSUE TITLE
Invalid Api-key format error -2014

### ISSUE THREAD

**Issue by gathuaalex** [CyberPunkMetalHead/Binance-volatility-trading-bot#112]
i'm using Testnet api keys 

but on running the script i get error -2014 . what might be the issue?

**Comment by DMKesseler** [comment]
According to the documentation it means the API key format is wrong

-2014 BAD_API_KEY_FMT
API-key format invalid.

**Comment by O-Mutt** [comment]
Yup, this is an api key error. If you get the latest code you should get a "pretty" error instead of this.
