### ISSUE TITLE
Make it clearer whether units are seconds or minutes in config

### ISSUE THREAD

**Issue by DarrenSmallwood** [CyberPunkMetalHead/Binance-volatility-trading-bot#115]
It's not clear in the config file whether the units are seconds or minutes for each setting. 

For example: TIME_DIFFERENCE states that it's minutes in the comment but RECHECK_INTERVAL doesn't.

**Comment by MikkMakk** [comment]
Because recheck interval is not a time unit it says how many times the Prices are checked. 

Time differnce 2 minutes
Recheck 120

This results in pricecheck (if TP or SL is reached) every second.
