### ISSUE TITLE
APIError(code=-2010): Account has insufficient balance for requested action.

### ISSUE THREAD

**Issue by LewisLebentz** [CyberPunkMetalHead/Binance-volatility-trading-bot#12]
I've had the bot running for a few hours, worked around #1 by adding in a sleep, so it has been successfully buying crypto. The bot hadn't had the opportunity to sell until now and it failed to sell saying insufficient balance despite attempting to sell the exact amount it bought earlier:

DOGEUSDT has gained 3.106% in the last 5 minutes, calculating volume in USDT
 preparing to buy 35.2 DOGEUSDT

TP or SL reached, selling 35.2 DOGEUSDT...
APIError(code=-2010): Account has insufficient balance for requested action.

May be an issue with python-binance? Can't see a reason binance would reject that though, I'll leave it running a bit longer and see if it triggers again, if it fails again I'll try a manual sell.

**Comment by LewisLebentz** [comment]
It's just tried to sell a different coin now and failed again:

TP or SL reached, selling 2.71 RLCUSDT...
APIError(code=-2010): Account has insufficient balance for requested action.
TP or SL not yet reached, not selling ATMUSDT for now...
not enough time has passed yet...

**Comment by LewisLebentz** [comment]
I think it may be to do with the precision of the amounts I've bought, in the json file I have this currently:

`{
    "DOGEUSDT": {
        "symbol": "DOGEUSDT",
        "orderid": 928084000,
        "timestamp": 1620591984979,
        "bought_at": "0.56763000",
        "volume": 35.2
    },
    "RLCUSDT": {
        "symbol": "RLCUSDT",
        "orderid": 257169001,
        "timestamp": 1620592596234,
        "bought_at": "7.36950000",
        "volume": 2.71
    },
    "ATMUSDT": {
        "symbol": "ATMUSDT",
        "orderid": 27337300,
        "timestamp": 1620592601728,
        "bought_at": "10.45600000",
        "volume": 1.913
    }
}`

**Comment by LewisLebentz** [comment]
Ok I figured it out, the volume logged is actually incorrect.

For RLC for example, the json file says I have 2.71. If I check Binance it says: 2.70783200. I'm new to Binance, so I'm guessing it's taking a fee out of the order, or there's some rounding going on.

I _believe_ if you hold some BNB it pays the fee with that instead so I guess that could be a workaround.

**Comment by CyberPunkMetalHead** [comment]
Yes, that's correct. I think the way is to only sell 99.5% of the coin. Trying a new implementation out now.

**Comment by CyberPunkMetalHead** [comment]
Also, I will close this ticket for now since we already have this issue in #8
