### ISSUE TITLE
Time-Outs to https://scanner.tradingview.com

### ISSUE THREAD

**Issue by NVQXE23I** [CyberPunkMetalHead/Binance-volatility-trading-bot#126]
In my logfile I have multiple errors per hour of connection problems:
`[2021-05-19 15:18:54] HTTPSConnectionPool(host='scanner.tradingview.com', port=443): Max retries exceeded with url: /crypto/scan (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff7d24dc580>, 'Connection to scanner.tradingview.com timed out. (connect timeout=10)'))`

Can these errors be handled more elegant?

**Comment by ShogunMan** [comment]
Sure, go ahead.
