### ISSUE TITLE
Your API key is either incorrect, IP blocked, or incorrect tld/permissons...

### ISSUE THREAD

**Issue by gathuaalex** [CyberPunkMetalHead/Binance-volatility-trading-bot#127]
Guys, I'm still getting  ```*API-key format invalid.*``` error even after regenerating new keys at ```https://testnet.binance.vision/key/generate``` what might be the issue?  I've taken the whole searching for this error but I got no solution.

**Comment by getsec** [comment]
Testnet is gone now. Prod only. If you use TEST_MODE TRUE. in config it uses prod keys but doesn’t buy anything
