### ISSUE TITLE
Incorrect BNB market buy price

### ISSUE THREAD

**Issue by bgitty** [CyberPunkMetalHead/Binance-volatility-trading-bot#13]
Hi thanks for the bot. I'm running against TESTNET and changed variables to trigger a buy if coins moved more than 1% in 1 min (100USDT max). It just brought BNB since it said it gained 26.24% in the last 1 min which isn't right since that would mean it moved around $170 in the last minute. BNB price for the last hour has been between 650 and 665 so how could it move $170? The JSON said it brought it for $585.
![boterr1](https://user-images.githubusercontent.com/83926791/117590336-f561b300-b0fc-11eb-8d72-86808405a74a.jpg)
 Timestamp for the buy: 7:17PM EST. I included a screencap. Thanks for your help!

**Comment by CyberPunkMetalHead** [comment]
I had the same issue while trying this out on the testnet, my guess is that the testnet is not all that great for testing and quite unreliable actually. I've been running it on the mainnet with a small amount just to test and I haven't been getting that error.
