### ISSUE TITLE
Binance.us account

### ISSUE THREAD

**Issue by abhistr13** [CyberPunkMetalHead/Binance-volatility-trading-bot#143]
Not really an issue, but wanna know if this would work with a Binance.us account? Or it does not really matter?

**Comment by flo-joe** [comment]
It does work with Binance.US but you have to make some small modifications.
1. Change client code in "Binance Detect Moonings.py" to add tld = 'us'
From:
`client = Client(access_key, secret_key)`
To:
`client = Client(access_key, secret_key, tld='us')`

2. Change ticker list to use USDT compatible tickers supported in Binance.US. See pull request #120

**Comment by ShogunMan** [comment]
Fixed in config.yml
