### ISSUE TITLE
Always on 0

### ISSUE THREAD

**Issue by mac-oya** [CyberPunkMetalHead/Binance-volatility-trading-bot#147]
Always say not holding any coins.
Signalsample: No coins above 18 threshold on both timeframes. Waiting 4 minutes for next analysis
[2021-05-25 00:45:21] Working...Session profit:0.00% Est:$0.00 
now more than 10 hours
what am I missing

**Comment by omani16** [comment]
The same problem!

**Comment by mindflvx** [comment]
It means what it says: there are no coins that meet the criteria.

To get more hits you can lower "TA_BUY_THRESHOLD" in signalsamplemod.py.

**Comment by lavaground** [comment]
Are you running the latest version of the bot?

**Comment by mac-oya** [comment]
> Are you running the latest version of the bot?

yes.

**Comment by mac-oya** [comment]
> It means what it says: there are no coins that meet the criteria.
> 
> To get more hits you can lower "TA_BUY_THRESHOLD" in signalsamplemod.py.

thanks it shows something now although another issue has risen, to do with : Account has insufficient balance for requested action.

**Comment by minikasamur** [comment]
send the link of the latest version of the bot?
