### ISSUE TITLE
No sufficient balance

### ISSUE THREAD

**Issue by mac-oya** [CyberPunkMetalHead/Binance-volatility-trading-bot#150]
Account has insufficient balance for requested action.
Where do i edit the parameter to do with this?

**Comment by ShogunMan** [comment]
Dude, read Wiki & Faq.

**Comment by mac-oya** [comment]
> Dude, read Wiki & Faq.

i ddnt see, let me look

**Comment by mac-oya** [comment]
But still it does not make sense, can someone simplify the configurations to do with say X USDT capital,

**Comment by mac-oya** [comment]
Also what i see is that you have to keep loading the USDT because the bot buys other coins then says no sufficient balance, please clarify my case, else i miss something
