### ISSUE TITLE
close after 5 mins passed

### ISSUE THREAD

**Issue by swardbeast** [CyberPunkMetalHead/Binance-volatility-trading-bot#16]
First of all thank you for creating this awesome script, but after the update is no longer working for me. 

![image](https://user-images.githubusercontent.com/83932671/117596617-4cf03500-b176-11eb-8d09-0adff64089e2.png)

It will basically closed after this this issue is not seen on the previous version. Am I missing anything on the update? thanks again.

**Comment by swardbeast** [comment]
update:
I remove the last 2 lines and change it to sell_coind(), will solve the issue. seems like something to do with my portfolio
coins_sold = sell_coins()
remove_from_portfolio(coins_sold)

**Comment by notflip** [comment]
> update:
> I remove the last 2 lines and change it to sell_coind(), will solve the issue. seems like something to do with my portfolio
> coins_sold = sell_coins()
> remove_from_portfolio(coins_sold)
> 
> another question is that, do we need to create the portolio/json file ourself or it will automatically create for us? because i am not seeing this files in the folders after i run.

The json file was created automatically for me, running on mac

**Comment by getsec** [comment]
Pull latest commit.
