### ISSUE TITLE
Can't sell because of the wrong  calculated volume.

### ISSUE THREAD

**Issue by Tau-hub** [CyberPunkMetalHead/Binance-volatility-trading-bot#17]
I use the livenet with 15$.

The bot bought : 

![Binance_PAFM66Irh0](https://user-images.githubusercontent.com/60314658/117613972-f0861900-b167-11eb-9e65-516a20b08b20.png)

in the .json file : 

![cmd_J2F5MYYQpk](https://user-images.githubusercontent.com/60314658/117614028-0693d980-b168-11eb-85fd-cbcaeabd0c9d.png)

when trying to sell I get insufficient amount : 

![cmd_DBLvnx89Tm](https://user-images.githubusercontent.com/60314658/117614112-21664e00-b168-11eb-9d2b-f611b956aa51.png)

Binance took fees directly on  the coin which decreased my volume : 
![image](https://user-images.githubusercontent.com/60314658/117614820-27a8fa00-b169-11eb-9e8c-bf575b23db30.png)

A solution would be to check our wallet and if the volume of a coin in our wallet is below what we should have we replace it with the volume in the wallet

**Comment by ErenYuksel-RMIT** [comment]
It should be the minimum of either the coin in our wallet, or the coin obtained when bought.

**Comment by CyberPunkMetalHead** [comment]
I have pushed a new commit to the main branch, this should have solved the issue.
