### ISSUE TITLE
Stop loss and Take Profit

### ISSUE THREAD

**Issue by aadam5888** [CyberPunkMetalHead/Binance-volatility-trading-bot#172]
Hi there,
Why is the stop loss not in decimals, but the take profit is. Initially, the stop loss was at 4 and the take profit was at 0.8. Is this a typo or an integral part of the program ?

**Comment by amitman3** [comment]
Hi,

Are you referring to the values from **config.yml**?
![Screenshot 2021-06-02 223004](https://user-images.githubusercontent.com/22363239/120522397-ce905700-c3f2-11eb-9033-dc4c91ed3cf3.jpg)


I believe those are editable and you can also set the stop loss value in decimals (example **.9**).

**Comment by Albert-Gao** [comment]
So, if as the description, `define in %`, 
- then `STOP_LOSS: 5` means `5%`? 
- While `TAKE_PROFIT: .8` means `0.008%`?
Am I right?

**Comment by hammy9696** [comment]
I th

> So, if as the description, `define in %`,
> 
> * then `STOP_LOSS: 5` means `5%`?
> * While `TAKE_PROFIT: .8` means `0.008%`?
>   Am I right?

.8 will mean 0.8% I'm guessing

**Comment by hammy9696** [comment]
> Hi,
> 
> Are you referring to the values from **config.yml**?
> ![Screenshot 2021-06-02 223004](https://user-images.githubusercontent.com/22363239/120522397-ce905700-c3f2-11eb-9033-dc4c91ed3cf3.jpg)
> 
> I believe those are editable and you can also set the stop loss value in decimals (example **.9**).

So by default its set at 5% take loss and 0.8% take profit, am i right?

**Comment by Albert-Gao** [comment]
Confirmed in the channel, 5 means 5% percent

**Comment by ShogunMan** [comment]
Not an issue, check faq, docs and discord.
