### ISSUE TITLE
Your API key is either incorrect, IP blocked, or incorrect tld/permissons...

### ISSUE THREAD

**Issue by co2netto** [CyberPunkMetalHead/Binance-volatility-trading-bot#180]
Because I have little programming knowledge, I have been following this guide and finally able to run it.

[https://www.cryptomaton.org/2021/05/08/how-to-code-a-binance-trading-bot-that-detects-the-most-volatile-coins-on-binance/](url)

It seems to have no problem with the API and has placed some order.

However, when I try the Binance Detect Moonings.py , it has the error: 

Your API key is either incorrect, IP blocked, or incorrect tld/permissons...
  most likely: Your API key is not formatted correctly...
  If you are in america, you will have to update the config to set AMERICAN_USER: True
  If you set an IP block on your keys make sure this IP address is allowed. check ipinfo.io/ip

I try adding ' ' to the API key and it is still the same. Is there something that I have missed?

**Comment by HiddevH** [comment]
Are you able to share how your creds.yml file looks like? It suggests an API Key formatting error so best to first exclude that.
!!!!! Please replace your actual API Keys with some random value when you share.

**Comment by nnnightt** [comment]
Having the same issue, copied my keys from another project that works and can successfully use the binance-api library. Also tried creating new keys, same thing.

**Comment by co2netto** [comment]
> Having the same issue, copied my keys from another project that works and can successfully use the binance-api library. Also tried creating new keys, same thing.
> 
> Also, if I try to query for something in here, it also works.
> 
> ```python
>     # Authenticate with the client, Ensure API key is good before continuing
>     if AMERICAN_USER:
>         client = Client(access_key, secret_key, tld='us')
>     else:
>         client = Client(access_key, secret_key)
>         prices = client.get_all_tickers()
>         print(prices)
> ```
> 
> Update 2:
> 
> You need to set the new API URL if using the testnet, else it's a legacy URL that doesn't allow some functions like 'get_aacount'. You should add this somewhere if the user is using the testnet:
> 
> ```python
>     client.API_URL = 'https://testnet.binance.vision/api'
> ```
> 
> Now it's working great! Thanks for this repo

Thank you sir!

I have only added API_URL code below the line
client = Client(access_key, secret_key)

and it is working!
