### ISSUE TITLE
account has insufficient balance for requested action

### ISSUE THREAD

**Issue by celltronic01** [CyberPunkMetalHead/Binance-volatility-trading-bot#189]
I just can't seem to be able to get this to work despite of all the corrections and tries. I am by no means a programmer but I have gone thru the whole GitHub file and done all the updates, corrections, etcetera but I am still getting this error. 

"Account has insufficient balance for requested action"  the volume on the Coins_Bought.json for each coin matches the volume on my Binance wallets which i had to manually adjust because i am not using BNB

Please help

Thank You

**Comment by ShogunMan** [comment]
Dude, read the wiki and faq. This has been answered so many times that i've lost count. You have to use BNB for paying fees.

**Comment by m3a4s** [comment]
mr.ShogunMan ;  can I use USDT to Buy the fees ? 

and if it possible how ?
