### ISSUE TITLE
APIError(code=-1013): Filter failure: LOT_SIZE shows after new update.

### ISSUE THREAD

**Issue by pekac45** [CyberPunkMetalHead/Binance-volatility-trading-bot#19]
`APIError(code=-1013): Filter failure: LOT_SIZE` is a new error which happens after the                 `sell_amount = coins_bought[coin]['volume']*99.25/100` is added. Some currencies are not able to be traded with this amount as they need a integer.

**Comment by CyberPunkMetalHead** [comment]
I'm getting the same issue but it doesn't seem to apply for all the coins. 
For example WANUSDT sold 
`TP or SL reached, selling 5.87 WANUSDT...
not enough time has passed yet.`

While SHIBUSDT failed

`TP or SL reached, selling 413618.0 SHIBUSDT...
APIError(code=-1013): Filter failure: LOT_SIZE
not enough time has passed yet..`

Definitely an odd one

**Comment by CyberPunkMetalHead** [comment]
Ok I know what's going on here. For coins that cannot return a step size in decimals, the code will automatically convert it to one decimal point: 413618.0. I'm guessing, but I suspect that 413618 would pass.
Need to figure out a way to apply this without disrupting the accurate volumes

**Comment by korsgaard** [comment]
Getting the same error, keep up the good work! ;-)

**Comment by CyberPunkMetalHead** [comment]
Have pushed another update, I have tested on 3 different coins and the LOT_SIZE error seems to be gone :)

**Comment by korsgaard** [comment]
Didn't get it yet!

**Comment by krczk** [comment]
It's working perfect 👍

**Comment by CyberPunkMetalHead** [comment]
That's odd, I specifically tested on SHIBUSDT and it sold without issues. Do you maybe have some unsold coins with the wrong volume format in your json file?

**Comment by phroton** [comment]
Sorry @CyberPunkMetalHead

```
TP or SL reached, selling 729.3 TRXUSDT...
APIError(code=-1013): Filter failure: LOT_SIZE
```

**Comment by CyberPunkMetalHead** [comment]
I have removed the CAPPED SELL SINCE IT DIDN'T HELP, have pushed (hopefully) a stability fix for the sell function. Been testing it throughout the day and it's proven to be quite stable.

**Comment by cweiner20** [comment]
�[91mTP or SL reached, selling 48.4 CTSIUSDT - 1.032 - 1.13995 : 10.46%�[39m
APIError(code=-1013): Filter failure: LOT_SIZE

**Comment by rodrigogs** [comment]
Still not working after the recent push.

**Comment by rodrigogs** [comment]
Fixed, just buy some BNB
