### ISSUE TITLE
Mainnet Fail to trade

### ISSUE THREAD

**Issue by gregheade** [CyberPunkMetalHead/Binance-volatility-trading-bot#190]
I have tried a live trade and get an error when trying to trade the coins back to USDT. So the first trade work USDT > coin, but the reverse doesnt.

APIError(code=-2010): Account has insufficient balance for requested action.

**Comment by ShogunMan** [comment]
Read FAQ & Wiki, This is not an issue.

**Comment by gregheade** [comment]
The issue in FAQ is not the same as  the one I am describing. I have more than enough USDT, this is about when the BOT tries to trade back to USDT I get the error.

**Comment by ShogunMan** [comment]
Read again. You have BNB in your account and set 'pay fees in BNB'?
