### ISSUE TITLE
No module named 'binance'

### ISSUE THREAD

**Issue by GoodGuyNick** [CyberPunkMetalHead/Binance-volatility-trading-bot#192]
Yesterday everything was fine and now I get this error. I didn't touch anything except config, trades and tickers.
```
 Binance-volatility-trading-bot-main python3 Binance\ Detect\ Moonings.py
Traceback (most recent call last):
  File "Binance Detect Moonings.py", line 34, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance'
```

**Comment by Kashkun** [comment]
new here trying to get my questions answered as well found this from the original article and it removed that error



pip install requests
pip install numpy
pip install python-binance
pip install nltk

**Comment by GoodGuyNick** [comment]
> new here trying to get my questions answered as well found this from the original article and it removed that error
> 
> pip install requests
> pip install numpy
> pip install python-binance
> pip install nltk

Installing `python-binance` was enough. Thank you.
But why in was working before without this package?

**Comment by getsec** [comment]
Most likely you werent in your virtual environment.
