### ISSUE TITLE
Move configuration items to JSON file

### ISSUE THREAD

**Issue by andrewsauter-nbcuni** [CyberPunkMetalHead/Binance-volatility-trading-bot#2]
https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/blob/0343a3d9329a40eb19ae9e4c25bad0021b9fcbcc/Binance%20Detect%20Moonings.py#L30

Since this will largely be used by people without coding experience, I would put all configuration items in a separate JSON config file. This will make it easier to read and less confusing for people to configure and setup properly.

**Comment by riolcrt** [comment]
I think it's more dangerous do it that way, because with no coding experience your API key could end online by accident if it's written in a file.

**Comment by andrewsauter-nbcuni** [comment]
@riolcrt I'm not following, it's already in a file. I'm suggesting he take it out of the main file where the code is. Literally no difference in functionality, just less confusing for people to configure.

**Comment by Selich** [comment]
I could add .env and do a PR.  Already planed to do that locally.

**Comment by getsec** [comment]
Keys now in creds.yml creds.yml is gitignored.
