### ISSUE TITLE
Doesn't check coin from the Binance innovation zone

### ISSUE THREAD

**Issue by Yorium** [CyberPunkMetalHead/Binance-volatility-trading-bot#22]
The bot does not check coin added in the innovation zone, for example SHIB (SHIBA) was listed will the bot was running, getting more that 3% increase and was not scanned by the bot.

**Comment by Yorium** [comment]
I'm currently on the testnet, could it be that ? i suppose

**Comment by manub** [comment]
The bot has been buying SHIB on mainnet for me.

**Comment by Yorium** [comment]
I just saw the testnet only have few coins, that is why
