### ISSUE TITLE
TP or SL reached, selling 0.001765 BTCUSDT... APIError(code=-1013): Invalid quantity.

### ISSUE THREAD

**Issue by L0Y4L** [CyberPunkMetalHead/Binance-volatility-trading-bot#29]

**Comment by phroton** [comment]
same problem here

**Comment by dhpatel548** [comment]
Seems that the purchase qty - fees is not showing when trying to sell, so it results in error.

**Comment by CyberPunkMetalHead** [comment]
I have pushed (hopefully) a stability fix for the sell function. Been testing it throughout the day and it's proven to be quite stable my side.

**Comment by manub** [comment]
actually by looking at the code it tries to sell the quantity listed in the `volume` field of `coins_bought.json`, however if I check my wallet that volume is not correct. e.g. volume states `1.357` while my Binance iOS app says I own `1.355643`. could this be the issue?

**Comment by phroton** [comment]
> actually by looking at the code it tries to sell the quantity listed in the `volume` field of `coins_bought.json`, however if I check my wallet that volume is not correct. e.g. volume states `1.357` while my Binance iOS app says I own `1.355643`. could this be the issue?

Are these 0.001357 maybe your transaction fee? @dhpatel548 commented this case before

**Comment by manub** [comment]
Yeah - I think a change could be to fetch the actual quantity before pushing the sell order.

**Comment by pawelantczak** [comment]
@manub so it is trying to sell more than you have, I have same errors. It seems that there is some rounding happening @CyberPunkMetalHead. It can't fetch balance from Binance, since you can have more on your account than bot bought.

**Comment by phroton** [comment]
maybe the API gives the correct value of the purchased coins. Then they could be returned at the end of buy()

**Comment by dhpatel548** [comment]
@phroton  the API does return the actual qty bought, but seems that is not the value the script is using.  It is using the calculated value when buying the coin unless I am reading the code wrong.

**Comment by phroton** [comment]
> @phroton the API does return the actual qty bought, but seems that is not the value the script is using. It is using the calculated value when buying the coin unless I am reading the code wrong.

yes, thats right - it returns the volume that has been given to buy() - but thats not the real volume

**Comment by jrocaspana** [comment]
maybe we can do something like (I'm not familiar with python sintaxis so this may not make any sense, but I think you will get the idea)
```py
                buy_limit = client.create_order(
                    symbol = coin,
                    side = 'BUY',
                    type = 'MARKET',
                    quantity = volume[coin]
                )

                volume[coin] = buy_limit['executedQty']
```
Binance API create order response docs can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#new-order--trade)

**Comment by pawelantczak** [comment]
@CyberPunkMetalHead this could be it ^^^

**Comment by getsec** [comment]
Pretty sure this is fixed in latest. Closing old issues so we can start from latest commit.

**Comment by Swimtoto** [comment]
Using the last version, I still have this issue. Today with different pairs (FIL, XMR, SOL, IOTX, ICP, UTK, XEM, TROY...)
I can identify where in the code, it has been fixed?
