### ISSUE TITLE
Coins should be deleted rather than made null/None

### ISSUE THREAD

**Issue by ErenYuksel-RMIT** [CyberPunkMetalHead/Binance-volatility-trading-bot#3]
After a coin is sold via the bot, it updates `coins_bought` by updating it's entry in the list to `None`, and it saves in the JSON file as `null`. 

We should probably have a null check to see if the entry in coins_bought is null? I just had another crash as the bot tried to use get a previously sold coin's TP/SL by checking coins_bought, but of course the entry was `None` and as it tried to access some property, it threw an exception. 

I'd make a pull request, but I haven't forked this repository.

**Comment by mindflvx** [comment]
Noticed the same issue.

**Comment by CyberPunkMetalHead** [comment]
New commit deletes coins entirely now
