### ISSUE TITLE
join the Binance-volatility-trading-bot discord 

### ISSUE THREAD

**Issue by CK92149** [CyberPunkMetalHead/Binance-volatility-trading-bot#33]
I wasn't sure where to post this, maybe CyberPunkMetalHead wants to post the link in the readme.txt

I've been using the bot and i'd like to discuss what values etc work well for other people. or for general questions

https://discord.gg/SqajQ8Tc

Regards

**Comment by getsec** [comment]
Thank you @CK92149  for your service <3
