### ISSUE TITLE
Differentiate between a TP and SL when Selling

### ISSUE THREAD

**Issue by BenMajestix** [CyberPunkMetalHead/Binance-volatility-trading-bot#39]
I Think its more informative when you know if the Program has been selling cause of a SL or TP. I will try to implement that feature : )

**Comment by pawelantczak** [comment]
I would extend this to better logging in general. Current % of gain/loss for coins we bought on every cycle for example.

**Comment by O-Mutt** [comment]
ref #54

**Comment by DrWilder** [comment]
This was easy to do. But my coding style is messy so I wont submit anything yet

**Comment by getsec** [comment]
implemented.
