### ISSUE TITLE
Additional time difference

### ISSUE THREAD

**Issue by MikkMakk** [CyberPunkMetalHead/Binance-volatility-trading-bot#40]
Is there a reason there isnt a second time difference?
In the scenario where it placed an order and it succesfully bought the coin it would make more sense to check the price for this coin/s more often than the initial time difference where it looks for a trend.

**Comment by mae2k17** [comment]
I was thinking about this too. The bot catches the initial hype from a move, but by the time it sells, it misses the window. To make up this difference I'm testing on mainnet using;

TIME_DIFFERENCE = 1

CHANGE_IN_PRICE = 2

**Comment by CyberPunkMetalHead** [comment]
Definitely a good call, would mean making some of the functions async and changing the execution, but I will look into it
