### ISSUE TITLE
Moving average

### ISSUE THREAD

**Issue by pawelantczak** [CyberPunkMetalHead/Binance-volatility-trading-bot#41]
Hi.

Nice work, thanks.

What do you think about adding MA?
Bot can query binance every 1m for instance and consider price from n last queries.

**Comment by CyberPunkMetalHead** [comment]
Actually, I'm thinking to integrate an RSI indicator to ensure that the bot doesn't buy when the coin is already overbought

**Comment by pawelantczak** [comment]
Buying decision based on RSI sounds good, but my issue is that bot is checking price too rarely. 
3% price rise in last 5 minutes is fine, but querying for TP and ST could be done every 1m for example.

**Comment by theGASK** [comment]
minimum kline interval seems to be 1m, so why not go for it.

**Comment by DrWilder** [comment]
So I increased the poll time to 30 seconds without issue. Still waiting for enough data to review the trends.

I have disabled the buy and sell code, while maintaining a record of anticipated profit and loss.

**Comment by ShogunMan** [comment]
This is available in mods now.
