### ISSUE TITLE
Sell before buy

### ISSUE THREAD

**Issue by pawelantczak** [CyberPunkMetalHead/Binance-volatility-trading-bot#42]
Hi.

Currently, buy operation is executed first.
With limited funds, it would be better to sell first and be able to buy in same cycle.

**Comment by ShogunMan** [comment]
Change this:

 for i in count():
        orders, last_price, volume = buy()
        update_porfolio(orders, last_price, volume)
        coins_sold = sell_coins()
        remove_from_portfolio(coins_sold)

to this:

 for i in count():
        coins_sold = sell_coins()
        remove_from_portfolio(coins_sold)
        orders, last_price, volume = buy()
        update_porfolio(orders, last_price, volume)

**Comment by CyberPunkMetalHead** [comment]
Good input, I've been testing this my end and it works nicely. I will most likely push the changes
