### ISSUE TITLE
wrong in pricing

### ISSUE THREAD

**Issue by lolongcovas** [CyberPunkMetalHead/Binance-volatility-trading-bot#43]
I got a wrong pricing for `ETHUSDT`: 150$

![image](https://user-images.githubusercontent.com/3662732/117869813-8ec6cb80-b29b-11eb-84b1-b64f5d92f114.png)

**Comment by ShogunMan** [comment]
Are you using the testnet? The prices there are just for testing purposes, and not live market prices.

**Comment by leerobinson82** [comment]
How can you test the effectiveness of the bot and parameter change without real world sample data?

**Comment by ShogunMan** [comment]
You can test the functionality on the testnet. Parameters and performance is tested on the live net with small amounts.

**Comment by lolongcovas** [comment]
I thought that testnet also considers the real price. thanks

**Comment by CondorUK** [comment]
There is an easy fix for this, create a client2 with the live APIs when you setup the testnet connection. Then in get_prices query client2 if testnet=true

**Comment by ShogunMan** [comment]
The testnet has a very limited selection of coins, so testing parameters by pulling the prices from the live net would take a long time as you will not get many trades.
