### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by joban727** [CyberPunkMetalHead/Binance-volatility-trading-bot#45]
syntax error - "Line 134 print(f'not enough time has passed yet...')"

any fix?

**Comment by bilalkhann16** [comment]
Try:
```
print ("not enough time has passed yet...")
```

**Comment by Amraki** [comment]
See #26 for replacement code for that line.
Might be handy to keep an eye on Pull Requests periodically to see if others have implemented new features. 
Insert standard warning to make changes with caution, of course.

**Comment by joban727** [comment]
Now getting
`    print(f'Not enough time has passed yet, will wait {TIME_DIFFERENCE} {"minutes" if TIME_DIFFERENCE > 1 else "minute"}...')
        ^
IndentationError: expected an indented block
`

**Comment by ShogunMan** [comment]
What does the line before this line read?
