### ISSUE TITLE
gives too many errors. lost 10usdt for not selling

### ISSUE THREAD

**Issue by yubina** [CyberPunkMetalHead/Binance-volatility-trading-bot#49]
was not a very healthy study. it doesn't work right

**Comment by O-Mutt** [comment]
What errors are you seeing? Why did you run in production mode with real money if you don't trust the codebase? The lost usdt is on you at this point imo

**Comment by yubina** [comment]
gives api error when selling.many people get the same error.

**Comment by O-Mutt** [comment]
If you would like to help move the project forward an error message or error code would be helpful. If you are experiencing an error that is already listed in a ticket maybe you could comment on that ticket or give an 👍 on the other ticket instead of opening up another one. 🎉

**Comment by yubina** [comment]
Of course I would like to help. I'll try again later with real money. I will inform you of the error. Binance gives api error because there are too many transactions. tickers, I wanted to change the tickers list myself but it doesn't see the list.I have encountered the same problem with the bot programs I have used before. Too many api do not accept transactions.
