### ISSUE TITLE
APIError(code=-1013): Filter failure: MIN_NOTIONAL

### ISSUE THREAD

**Issue by campbellkerr** [CyberPunkMetalHead/Binance-volatility-trading-bot#5]
![image](https://user-images.githubusercontent.com/38451588/117571258-1fbd6b80-b111-11eb-864f-a87305e6e251.png)

I've set the vars like this:
![image](https://user-images.githubusercontent.com/38451588/117571560-75464800-b112-11eb-97c7-24e4e46ce548.png)

This could be user error. It appears to mean the buy amount is too small?

I only have a small amount ( $50 AUD ) in binance. Is there any error handling or workarounds? Thanks!

**Comment by 21jake** [comment]
You have to raise the QUANTITY in order to make a successful request. IMO  10-15 USDT is enough. 

https://stackoverflow.com/questions/61582902/python-binance-api-apierrorcode-1013-filter-failure-lot-size

**Comment by CyberPunkMetalHead** [comment]
Thanks for answering that @21jake, @campbellkerr let me know if that fixes your issue and I will close this ticket.

**Comment by campbellkerr** [comment]
Thanks - I found 11 was the magic number. The MIN_NOTIONAL errors are gone!
