### ISSUE TITLE
Question about test order

### ISSUE THREAD

**Issue by O-Mutt** [CyberPunkMetalHead/Binance-volatility-trading-bot#50]
This code references placing real orders if the test order does not throw:
https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/blob/172cc44e33078f9fd33de3a7bace60f1fa8725a0/Binance%20Detect%20Moonings.py#L223-L238

In my test runs the throw crashes the app, is this expected behavior? I wouldn't expect to handle this code with a uncaught exception but instead log the exception 

e.g.
``` python
if TESTNET:
    # create test order before pushing an actual order
    try:
        test_order = client.create_test_order(symbol=coin, side='BUY', type='MARKET', quantity=volume[coin])

    except Exception as e:
        print(f'An error occurred placing the test order {e}')

    #try to create a real order if the test orders did not raise an exception
    try:
        buy_limit = client.create_order(
            symbol = coin,
            side = 'BUY',
            type = 'MARKET',
            quantity = volume[coin]
        )

     # error handling here in case position cannot be placed
      except Exception as e:
          print(e)
```

**Comment by djhashh** [comment]
bump

**Comment by getsec** [comment]
@O-Mutt This still happening?

**Comment by getsec** [comment]
No response. If happening. I need to know the exception please.
