### ISSUE TITLE
Adding Telegram Bot in order to receive updates

### ISSUE THREAD

**Issue by hExPY** [CyberPunkMetalHead/Binance-volatility-trading-bot#55]
Hey guys,

It would be great to have a `telegram` bot sending messages in order to keep yourself updated.
What do you think?
I could implement the solution in the next few days but not sure if it's a useful feature except for me.

**Comment by Finnskyyy** [comment]
I would like it, sounds very useful!

**Comment by marcelobarreto** [comment]
Yes, please!

**Comment by Versatil0** [comment]
Majestix in the discord have allready created it.

[Telegram talker.zip](https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/files/6472538/Telegram.talker.zip)

**Comment by getsec** [comment]
@hExPY  Can you not just monitor your Trade History on Binance?

**Comment by Gimpabompie** [comment]
Yes Please

**Comment by AnasAlmomany** [comment]
PR Created #99

**Comment by getsec** [comment]
see pr comments
