### ISSUE TITLE
APIERROR code 2015

### ISSUE THREAD

**Issue by lrisley** [CyberPunkMetalHead/Binance-volatility-trading-bot#59]
APIError(code=-2015): Invalid API-key, IP, or permissions for action.

I'm guessing this is for binance.com only and not binance.us?
Is there a way to get it to work with binance.us?

**Comment by shanbady** [comment]
i think* you can pass `tld='us'` when initializing the client.

**Comment by lrisley** [comment]
Thank you for the response.
Would that be something like client.tld = ('us')  ?
I tried just     tld='us'  and it did not change.
I put a print statement in to show me all the pairs it gets and that works fine so it seems like it is talking to one of the binances.
I know the keys pair is fine since it works  for me with quandancy.

**Comment by shanbady** [comment]
no it would be like `client = Client(api_key, api_secret, tld='us')`

**Comment by lrisley** [comment]
ok, I tried that and at least it is not erroring yet.
Just have to wait till a buy is posted (just getting "not enough time passed" and "no coins moved more than 3%).
Thanks again for your help.

**Comment by bumbleblee** [comment]
Can anyone confirm this fix helped? I've tried this fix on both the binance client.py file along with the Binance Detect Moonings.py file with no success. It changes the keypairs the bot pulls so it looks like it's targeting binance.us but still receives the APIError.

**Comment by getsec** [comment]
@bumbleblee the TLD issue does fix it. Please open your issue in a new issue .
