### ISSUE TITLE
APIError(code=-2010)

### ISSUE THREAD

**Issue by Mathiaszmrga** [CyberPunkMetalHead/Binance-volatility-trading-bot#61]
some transactions have more decimals than supported for some trades, a rounding function should fix this

**Comment by Mathiaszmrga** [comment]
I have no clue why this is happening, however placing a limit order with the market price seems to fix this issue and sell right after it's placed

**Comment by getsec** [comment]
This should have been addressed. Please clone main and try again. If it arises, please share stack traces, errors, and config. Cheers.
