### ISSUE TITLE
Suggestion - show warning for live vs TESTNET

### ISSUE THREAD

**Issue by campbellkerr** [CyberPunkMetalHead/Binance-volatility-trading-bot#7]
Another handy sanity check/debug idea. Could even use ANSI escape codes to make it stand out with colours!

![image](https://user-images.githubusercontent.com/38451588/117572087-a3c52280-b114-11eb-91fc-7b2a7634f2da.png)

```
else:
     print('WARNING - Using live funds!')
     client = Client(api_key_live, api_secret_live)
```

**Comment by CyberPunkMetalHead** [comment]
Great idea, I have pushed a new commit that's throwing a warning and also pauses for 30 seconds as safety mechanism before executing for the first time,
