### ISSUE TITLE
Testnet error or script? bnb price fetch

### ISSUE THREAD

**Issue by Zselter07** [CyberPunkMetalHead/Binance-volatility-trading-bot#72]
I just tried it now on Testnet. It can't get the correct price of bnb I guess, I got this same message for 10 minutes now, the price changed for sure, it was above 560. 

'TP or SL not yet reached, not selling BNBUSDT for now 558.23 - 558.23 : 0.00% '

Is this another testnet error or something might've gone wrong?

**Comment by mindflvx** [comment]
I'm seeing the same issue with the latest version and also with BNB, not sure what's the cause.

**Comment by mindflvx** [comment]
I actually believe this is an issue with testnet since it doesn't reflect the real market.

Someone more knowledgeable can probably confirm.

**Comment by yubina** [comment]
TP or SL reached, selling 38.65 OMUSDT - 0.3881 - 0.4359 : 12.32%
APIError(code=-2010): Account has insufficient balance for requested action.
TP or SL not yet reached, not selling FLMUSDT for now 0.9331 - 0.9359 : 0.30%
TP or SL not yet reached, not selling BTCSTUSDT for now 75.37 - 75.534 : 0.22%
TP or SL not yet reached, not selling TRUUSDT for now 0.3857 - 0.3924 : 1.74%
TP or SL not yet reached, not selling PERPUSDT for now 10.162 - 10.091 : -0.70%
TP or SL not yet reached, not selling SLPUSDT for now 0.2023 - 0.201 : -0.64%

same error comes up when selling

**Comment by getsec** [comment]
@mindflvx  Checkout our FAQ on [Discord](https://discord.gg/buD27Dmvu3)
