### ISSUE TITLE
What is TP and SL?

### ISSUE THREAD

**Issue by mengjin-tes** [CyberPunkMetalHead/Binance-volatility-trading-bot#80]

**Comment by mindflvx** [comment]
Take Profit, Stop Loss. Google is your friend to find out more.

**Comment by getsec** [comment]
@mengjin-tes  Check out https://www.investopedia.com/terms/s/stop-lossorder.asp

**Comment by mengjin-tes** [comment]
Thanks, I'm referring to your code to implement the version of golang. Thank you for your dedication.
