### ISSUE TITLE
Massive gaps in SPOT price

### ISSUE THREAD

**Issue by usoppu** [CyberPunkMetalHead/Binance-volatility-trading-bot#95]
TP or SL not yet reached, not selling BTCUSDT for now 48868.49 - 48551.76 : -0.65% 
TP or SL reached, selling 0.000307 BTCUSDT - 48868.49 - 9000.0 : -81.58%

Is binance just weird? 81.58% ??

**Comment by mindflvx** [comment]
That was on the testnet, right? Seen the same, it's very unreliable.

**Comment by usoppu** [comment]
yes. testnet
