### ISSUE TITLE
add a way to define the direction of the change in price (1.25+ / 1.25-)

### ISSUE THREAD

**Issue by Mathiaszmrga** [CyberPunkMetalHead/Binance-volatility-trading-bot#98]
This is both a question and a qol thing but ill close if its just me not understanding.
Is there a way to define or make it so that it only places trades on coins with a positive or negative "CHANGE_IN_PRICE: 1.25", whats the default and can I put negative numbers in there?

**Comment by 23Lapial** [comment]
"CHANGE_IN_PRICE" can be negative. In the code it says, "each coin with higher gains than our CHANGE_IN_PRICE is added to the volatile_coins dict if less than MAX_COINS is not reached." I believe the bot will consider more coins if "CHANGE_IN_PRICE" is negative. Is that what you want?

**Comment by Mathiaszmrga** [comment]
> "CHANGE_IN_PRICE" can be negative. In the code it says, "each coin with higher gains than our CHANGE_IN_PRICE is added to the volatile_coins dict if less than MAX_COINS is not reached." I believe the bot will consider more coins if "CHANGE_IN_PRICE" is negative. Is that what you want?

Yes, that works
